import Image from 'next/image'
import { Metadata } from 'next'
import Link from 'next/link'
import { useEffect } from 'react';

export const metadata: Metadata = {
  title: 'Shlist',
  description: 'Generated by create next app',
}

let isLoggedIn:boolean = false;

export default function Home() {
  return (<>
  {isLoggedIn ? (
    <h1>loged</h1>
    ) : (
      <h1>ekki loged in :(</h1>
    )
  }
    <h1>Shlist</h1>
    <Link href="login">LOGIN BITCH</Link>
    </>
  )
}
